package com.termux.privileged.lane;

import org.junit.Rule;
import org.junit.Test;
import org.junit.rules.TemporaryFolder;

import java.io.BufferedReader;
import java.io.File;
import java.io.IOException;
import java.io.StringReader;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;

import static org.junit.Assert.assertEquals;
import static org.junit.Assert.assertNotNull;
import static org.junit.Assert.assertNull;

/**
 * Plain JUnit against the engine's TSV shape (tlstore/engine/tlstore: field 6 is the digest,
 * field 9 the {@code ;}-separated options, and {@code pick_catalog} prefers the user's copy by
 * serial). A row that is not a {@code binary} with {@code priv=shizuku} must never match, no
 * matter how its digest lines up.
 */
public class PrivilegedCatalogTest {

    private static final String DIGEST_BTOP = "0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef";
    private static final String DIGEST_OTHER = "fedcba9876543210fedcba9876543210fedcba9876543210fedcba9876543210";
    private static final String DIGEST_PKG = "1111111111111111111111111111111111111111111111111111111111111111";

    /** name kind version prefixes source digest target requires options summary */
    private static String row(String name, String kind, String digest, String options) {
        return String.join("\t", name, kind, "1.0", "com.termux,io.vaj.tl", "binaries:" + name + "@1.0",
            digest, "~/.local/bin/" + name, "-", options, "A tool.", "System");
    }

    @Rule
    public TemporaryFolder folder = new TemporaryFolder();

    @Test
    public void aBinaryRowWithPrivShizukuMatchesByDigest() throws IOException {
        PrivilegedCatalog catalog = parse(
            "# tlstore catalog\tserial=2026092502\n"
                + "# name\tkind\tversion\n"
                + row("btop", "binary", DIGEST_BTOP, "host=launcher;priv=shizuku") + "\n");
        PrivilegedCatalog.Row row = catalog.findByDigest(DIGEST_BTOP);
        assertNotNull(row);
        assertEquals("btop", row.name);
        assertEquals(DIGEST_BTOP, row.digest);
    }

    @Test
    public void theOptionIsMatchedWholeAndAnywhereInTheList() throws IOException {
        PrivilegedCatalog catalog = parse(
            row("a", "binary", DIGEST_BTOP, "priv=shizuku") + "\n"
                + row("b", "binary", DIGEST_OTHER, "env=X=1;priv=shizuku;tz=1") + "\n"
                + row("c", "binary", DIGEST_PKG, "priv=shizukuish") + "\n");
        assertNotNull(catalog.findByDigest(DIGEST_BTOP));
        assertNotNull(catalog.findByDigest(DIGEST_OTHER));
        assertNull("priv=shizukuish is not priv=shizuku", catalog.findByDigest(DIGEST_PKG));
    }

    @Test
    public void rowsWithoutTheOptionOrOfAnotherKindNeverMatch() throws IOException {
        PrivilegedCatalog catalog = parse(
            row("fastfetch", "binary", DIGEST_OTHER, "host=launcher") + "\n"
                + row("something", "pkg", DIGEST_PKG, "priv=shizuku") + "\n"
                + row("plain", "binary", DIGEST_BTOP, "-") + "\n");
        assertNull(catalog.findByDigest(DIGEST_OTHER));
        assertNull(catalog.findByDigest(DIGEST_PKG));
        assertNull(catalog.findByDigest(DIGEST_BTOP));
        assertEquals(0, catalog.size());
    }

    @Test
    public void digestsCompareCaseInsensitivelyAndMalformedOnesAreSkipped() throws IOException {
        PrivilegedCatalog catalog = parse(
            row("btop", "binary", DIGEST_BTOP.toUpperCase(), "priv=shizuku") + "\n"
                + row("short", "binary", "abc123", "priv=shizuku") + "\n"
                + row("dash", "binary", "-", "priv=shizuku") + "\n");
        assertNotNull(catalog.findByDigest(DIGEST_BTOP));
        assertNotNull(catalog.findByDigest(DIGEST_BTOP.toUpperCase()));
        assertEquals(1, catalog.size());
    }

    @Test
    public void commentsBlanksAndShortRowsAreIgnored() throws IOException {
        PrivilegedCatalog catalog = parse("# comment\n\n" + "btop\tbinary\t1.0\n" + "\n");
        assertEquals(0, catalog.size());
    }

    @Test
    public void optionParsingFollowsTheEngine() {
        assertEquals("shizuku", PrivilegedCatalog.option("host=launcher;priv=shizuku", "priv"));
        assertEquals("", PrivilegedCatalog.option("priv=;x=1", "priv"));
        assertNull(PrivilegedCatalog.option("host=launcher", "priv"));
        assertNull("space is not a separator", PrivilegedCatalog.option("host=launcher priv=shizuku", "priv"));
        assertNull("comma is not a separator", PrivilegedCatalog.option("host=launcher,priv=shizuku", "priv"));
    }

    @Test
    public void serialComesFromTheHeaderComment() {
        assertEquals(Long.valueOf(2026092502L), PrivilegedCatalog.serialOfComment("# tlstore catalog\tserial=2026092502"));
        assertNull(PrivilegedCatalog.serialOfComment("# generated by scripts/build-catalog.sh"));
        assertNull(PrivilegedCatalog.serialOfComment("# serial="));
    }

    @Test
    public void theNewerUserCatalogWinsOtherwiseTheBase() throws IOException {
        File base = write("base.tsv", "# tlstore catalog\tserial=100\n" + row("btop", "binary", DIGEST_BTOP, "priv=shizuku") + "\n");
        File newerUser = write("newer.tsv", "# tlstore catalog\tserial=101\n" + row("btop", "binary", DIGEST_OTHER, "priv=shizuku") + "\n");
        File olderUser = write("older.tsv", "# tlstore catalog\tserial=99\n" + row("btop", "binary", DIGEST_PKG, "priv=shizuku") + "\n");
        File noSerialUser = write("noserial.tsv", row("btop", "binary", DIGEST_PKG, "priv=shizuku") + "\n");
        File missing = new File(folder.getRoot(), "missing.tsv");

        assertEquals(newerUser, PrivilegedCatalog.pick(base, newerUser));
        assertEquals(base, PrivilegedCatalog.pick(base, olderUser));
        assertEquals("a user copy without a serial is not trusted over the base", base, PrivilegedCatalog.pick(base, noSerialUser));
        assertEquals(base, PrivilegedCatalog.pick(base, missing));
        assertEquals(newerUser, PrivilegedCatalog.pick(missing, newerUser));
        assertNull(PrivilegedCatalog.pick(missing, missing));

        // And load() reads the one pick() chose.
        assertNotNull(PrivilegedCatalog.load(base, newerUser).findByDigest(DIGEST_OTHER));
        assertNull(PrivilegedCatalog.load(base, newerUser).findByDigest(DIGEST_BTOP));
        assertEquals(0, PrivilegedCatalog.load(missing, missing).size());
    }

    private static PrivilegedCatalog parse(String text) throws IOException {
        return PrivilegedCatalog.parse(new BufferedReader(new StringReader(text)));
    }

    private File write(String name, String text) throws IOException {
        File file = new File(folder.getRoot(), name);
        Files.write(file.toPath(), text.getBytes(StandardCharsets.UTF_8));
        return file;
    }
}
