#!/usr/bin/env python3

# Generates res/values/layouts.xml — the catalogue the launcher's layout picker
# and the layout hot-swap ring read — from the layout files in res/xml.
#
# Adapted from Unexpected-Keyboard's gen_layouts.py. Differences: the layouts
# are already resources here rather than sources under srcs/layouts, the arrays
# are prefixed inapp_ so they cannot collide with the app module's own, and
# there are no "system"/"custom" pseudo entries — the launcher owns those.
#
#     python3 inapp-keyboard/tools/gen_layouts.py

import os
import glob
import xml.etree.ElementTree as XML

HERE = os.path.dirname(os.path.abspath(__file__))
XML_DIR = os.path.join(HERE, "..", "src", "main", "res", "xml")
OUT = os.path.join(HERE, "..", "src", "main", "res", "values", "layouts.xml")

# The programming layouts lead the catalogue; everything else is alphabetical by
# display name, which is the order the picker shows.
FIRST_LAYOUTS = ["termux_launcher_qwerty", "latn_qwerty_us", "latn_colemak", "latn_dvorak"]


def read_layouts(files):
    for path in files:
        layout_id = os.path.splitext(os.path.basename(path))[0]
        root = XML.parse(path).getroot()
        # Rows (bottom_row, number_row) and the modal pads (numeric, numpad,
        # greekmath) carry no name and are not selectable layouts.
        if root.tag != "keyboard" or root.get("name") is None:
            continue
        yield (layout_id, root.get("name"))


def sort_layouts(layouts):
    layouts = dict(layouts)
    head = [(lid, layouts.pop(lid)) for lid in FIRST_LAYOUTS if lid in layouts]
    return head + sorted(layouts.items(), key=lambda kv: kv[1].lower())


def mk_array(tag, name, items):
    elem = XML.Element(tag, name=name)
    for value in items:
        item = XML.Element("item")
        item.text = value
        elem.append(item)
    return elem


def main():
    layouts = sort_layouts(read_layouts(sorted(glob.glob(os.path.join(XML_DIR, "*.xml")))))
    values, entries = zip(*layouts)
    root = XML.Element("resources")
    root.append(XML.Comment(
        text=" DO NOT EDIT. Generated by tools/gen_layouts.py from res/xml. "))
    root.append(mk_array("string-array", "inapp_layout_values", values))
    root.append(mk_array("string-array", "inapp_layout_entries", entries))
    root.append(mk_array("integer-array", "inapp_layout_ids",
                         ["@xml/%s" % lid for lid in values]))
    XML.indent(root)
    XML.ElementTree(element=root).write(OUT, encoding="utf-8", xml_declaration=True)
    print("Wrote %s with %d layouts" % (os.path.normpath(OUT), len(values)))


if __name__ == "__main__":
    main()
